"""Shared constants module.

This module provides stable orchestration identifiers shared across notebooks and scripts.
"""

from .orchestration import (
    STAGE_SMOKE,
    STAGE_HPO,
    STAGE_TRAINING,
    EXPERIMENT_NAME,
    MODEL_NAME,
    PROD_STAGE,
    CONVERSION_JOB_NAME,
    METRICS_FILENAME,
    BENCHMARK_FILENAME,
    CHECKPOINT_DIRNAME,
    OUTPUTS_DIRNAME,
    MLRUNS_DIRNAME,
    DEFAULT_RANDOM_SEED,
    DEFAULT_K_FOLDS,
)
from .mlflow import (
    DEFAULT_MLFLOW_MAX_RESULTS,
    MEDIUM_MLFLOW_MAX_RESULTS,
    LARGE_MLFLOW_MAX_RESULTS,
    SAFETY_MLFLOW_MAX_RESULTS,
    SMALL_MLFLOW_MAX_RESULTS,
    SAMPLE_MLFLOW_MAX_RESULTS,
    HASH_DISPLAY_LENGTH_SHORT,
    HASH_DISPLAY_LENGTH_MEDIUM,
    HASH_DISPLAY_LENGTH_LONG,
    ERROR_MESSAGE_DISPLAY_LENGTH,
    DEFAULT_STALE_MINUTES,
)

__all__ = [
    "STAGE_SMOKE",
    "STAGE_HPO",
    "STAGE_TRAINING",
    "EXPERIMENT_NAME",
    "MODEL_NAME",
    "PROD_STAGE",
    "CONVERSION_JOB_NAME",
    "METRICS_FILENAME",
    "BENCHMARK_FILENAME",
    "CHECKPOINT_DIRNAME",
    "OUTPUTS_DIRNAME",
    "MLRUNS_DIRNAME",
    "DEFAULT_RANDOM_SEED",
    "DEFAULT_K_FOLDS",
    # MLflow constants
    "DEFAULT_MLFLOW_MAX_RESULTS",
    "MEDIUM_MLFLOW_MAX_RESULTS",
    "LARGE_MLFLOW_MAX_RESULTS",
    "SAFETY_MLFLOW_MAX_RESULTS",
    "SMALL_MLFLOW_MAX_RESULTS",
    "SAMPLE_MLFLOW_MAX_RESULTS",
    "HASH_DISPLAY_LENGTH_SHORT",
    "HASH_DISPLAY_LENGTH_MEDIUM",
    "HASH_DISPLAY_LENGTH_LONG",
    "ERROR_MESSAGE_DISPLAY_LENGTH",
    "DEFAULT_STALE_MINUTES",
]








